FORMAT: 1A
/* HOST: http://polls.apiblueprint.org/ */

# Deloitte AssessmentTool

REST API for Deloitte Assessment Tool

# Group Projects

## Project List [/project]

### List Projects [GET]

+ Response 200 (application/json)
    + Attributes (array)
        + (Project)
        + (Project)
            + name: QuickScan 2
        + (Project)
            + name: QuickScan 3
            + customerName: Charisma Hospital
            + startDate: Aug 16, 2016 11:50:06 AM
        + (Project)
            + name: QuickScan 4
            + customerName: Charisma Hospital
        + (Project)
            + name: QuickScan 5
            + customerName: Charisma Hospital
            + startDate: Dec 16, 2016 11:50:06 AM
        + (Project)
            + name: QuickScan 6
            + startDate: Jan 16, 2017 11:50:06 AM

### Create Project [POST]

+ Request (application/json)

            {
                "name": "QuickScan 1",
                "startDate": "Jun 16, 2016 11:50:06 AM",
                "endDate": "Jun 16, 2016 11:50:06 AM",
                "benchmarking": true
            }

+ Response 201 (application/json)

    + Headers

            Location: /project/1

    + Body
    + Attributes (Project)

## Single Project [/project/{id}]

+ Parameters
    + id: 1 (number)

### Read Project [GET]

+ Response 200 (application/json)

    + Body
    + Attributes (Project)

### Update Project [PUT]

+ Response 204

### Delete Project [DELETE]

+ Response 204

# Data Structures

## Project (object)
- id: 123 (number)
- name: QuickScan 1 (string, required)
- case: Case 1 (string)
- startDate: Jun 16, 2016 11:50:06 AM (string, required)            
- endDate: Jun 16, 2016 11:50:06 AM (string, required)
- customerId: 10
- customerProjectLeaderId: 11
- customerName: Alpha Hospital
- serviceProviderId: 20
- serviceProviderProjectLeaderId: 21
- benchmarking: true,
- monitoring: true,
- comments: This is a comment